### ISSUE TITLE
premature close error on process exit

### ISSUE THREAD

**Issue by yocontra** [clinicjs/node-clinic#41]
## Expected Behavior

An HTML report should be saved

## Current Behavior

Doctor, bubbleprof, and flame all crash with this error:

```
Error: premature close
    at MultiStream.onclose (/Users/contra/.nvm/versions/node/v10.6.0/lib/node_modules/clinic/node_modules/end-of-stream/index.js:47:67)
    at MultiStream.emit (events.js:187:15)
    at MultiStream.destroy (/Users/contra/.nvm/versions/node/v10.6.0/lib/node_modules/clinic/node_modules/multistream/index.js:65:8)
    at DestroyableTransform.onClose (/Users/contra/.nvm/versions/node/v10.6.0/lib/node_modules/clinic/node_modules/multistream/index.js:111:12)
    at Object.onceWrapper (events.js:273:13)
    at DestroyableTransform.emit (events.js:187:15)
    at /Users/contra/.nvm/versions/node/v10.6.0/lib/node_modules/clinic/node_modules/through2/through2.js:20:10
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

## Steps to Reproduce (for bugs)
1. Node 10.6
2. `npm install clinic -g`
3. `clinic doctor -- node dummy-server.js`
4. Wait a bit, press CTRL-C

## Environment
* Clinic version: Clinic v1.1.0 Doctor v3.0.3
* Node version: v10.6
* Operating system and version: MacOS Mojave Beta

**Comment by AlanSl** [comment]
Hi Contra, we sometimes see this error if Clinic has not collected sufficient data, so perhaps there is not enough activity in the dummy server. Can you try:

- Installing autocannon - `npm i -g autocannon` if you do not have it already
- Running `clinic doctor --on-port 'autocannon http://localhost:$PORT' -- node dummy-server.js`

This will fire 10 seconds of requests at the dummy server.

**Comment by contra** [comment]
@AlanSl I'm running ~4K rpm at the webserver for 5-10 mins before hitting Ctrl-C when I have this issue.

**Comment by contra** [comment]
FWIW I usually run this fork of end-of-stream in my package.json `resolutions` to fix this error - https://github.com/mafintosh/end-of-stream/pull/13

Has been an outstanding bug with it for a long time.

**Comment by mafintosh** [comment]
Can you share a full test case, including the server code? Can't seem to reproduce.

**Comment by BridgeAR** [comment]
Ping @contra

**Comment by contra** [comment]
I can't share a full test case because this is private code, if I have a few hours to spare soon (unlikely) I'll try to come up with an isolated test case. The project is nothing special - express, newrelic, postgres via sequelize.

**Comment by omar-dulaimi** [comment]
Hello,
I'm facing the exact same issue, any suggestions on how to fix it?

**Comment by omar-dulaimi** [comment]
`    const result = await autocannon({
      url: 'url',
      connections: 15, //default
      pipelining: 1, // default
      duration: 60, // default
      requests: [
        {
          method: 'POST', // this should be a post for logging in
          path: 'url',
          body: JSON.stringify(addProduct),
          // overwrite our default headers,
          // so we don't add an auth token
          // for this request
          headers: { 'Content-type': 'application/json' }
        },]
    })`

**Comment by omar-dulaimi** [comment]
I'm running clinic doctor locally using this command:
 clinic doctor -- node server.js

and I have an end point that runs the autocanon code above. Am I missing something?

**Comment by KashiMoonactive** [comment]
I'm also running clinic doctor locally and having the same issue.
I am running 6 request per second for 5 minutes (total of 1800 requests)
Using clinic v4.2.0

**Comment by gajus** [comment]
Some issue using v13.0.1.

```
Error: premature close
    at onclosenexttick (/Users/gajus/.nvm/versions/node/v13.0.1/lib/node_modules/clinic/node_modules/end-of-stream/index.js:53:86)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

```

For what it is worth, the patch proposed in https://github.com/mafintosh/end-of-stream/pull/13, does solve _this_ problem.

**Comment by AndreMaz** [comment]
Same here. I'm using node v12.13.0.

```
Analysing dataError: premature close
    at onclosenexttick (/usr/lib/node_modules/clinic/node_modules/end-of-stream/index.js:53:86)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

Steps to repro:
1. Generate [Moleculer demo project](https://moleculer.services/docs/0.13/usage.html#Create-a-Moleculer-project)
2. Open the generated project, set `transporter` to `null` in `moleculer.config.js`
3. Run `clinic doctor -- npm run dev`
4. Run `autocannon http://localhost:3000/api/greeter/hello`
5. Press `Ctrl + C`

**Comment by goto-bus-stop** [comment]
It's started happening more with recent Node.js versions, I think. When this happens, one thing you can try is to generate the visualization manually using `--visualize-only`:

```
clinic doctor --visualize-only .clinic/{pid}.clinic-doctor
```
I find that it often still produces usable data.

Obviously it would be better if it just worked immediately, but i don't know how just yet! :upside_down_face:

**Comment by goldbergyoni** [comment]
> Hello,
> I'm facing the exact same issue, any suggestions on how to fix it?

Same here

**Comment by subiron** [comment]
+1

**Comment by CoaPsyFactor** [comment]
Try removing ".clinic" directory, it helped me.

**Comment by alanhr** [comment]
+1

**Comment by jrnail23** [comment]
I'm also having it on node 10.16.3.  The fix described in https://github.com/mafintosh/end-of-stream/pull/13 fixes it completely.

**Comment by jasnell** [comment]
@goto-bus-stop @DylanC ... let's make sure this issue is looked at for the next release.

**Comment by jrnail23** [comment]
Thanks for taking a look, @jasnell... to be clear, this error happens consistently any time I try to do any significant profiling runs.  In our case, running autocannon with 10 connections for more than 20 seconds or so is likely to experience this problem.

**Comment by jasnell** [comment]
Really that's unsurprising. That load is going to generate a significant amount of profile data that is just difficult to analyze without running out of memory during the analysis. We'll need to explore some alternative ways of churning through the data.

**Comment by jrnail23** [comment]
@jasnell, the thing is, I can run much larger profiles with no problems if I hack `end-of-stream` with that https://github.com/mafintosh/end-of-stream/pull/13 fix.

**Comment by goto-bus-stop** [comment]
I'm assuming it's a timing difference then as described in that PR. If we run out of memory, we're stopping the streams that read more data, so you can at least get the visualization for the stuff that was already read. Presumably the 'close' event that we fire here needs to be done at some other point (or be preceded by some other operation that makes it valid according to e-o-s).
https://github.com/nearform/node-clinic-doctor/blob/85d3bfb5a836234bfad0e18e4c9f33dfa7ed4549/lib/destroyable-stream.js#L14

**Comment by goto-bus-stop** [comment]
Doctor 4.1.0 did include a fix for _one_ of the causes of this error. Bubbleprof uses `multistream` which has a buggy `destroy()` implementation.

**Comment by hadihammurabi** [comment]
any suggention how to fix this?

**Comment by goto-bus-stop** [comment]
We've just finally published new Doctor and Bubbleprof versions that depend on patched forks of the buggy modules—could you try reinstalling Clinic.js and see if it still happens? Thanks!

**Comment by hadihammurabi** [comment]
Actually, it can help.
https://github.com/nearform/node-clinic/issues/41#issuecomment-572011417

But, i want to update it now.

**Comment by paolochiodi** [comment]
I've encountered this problem too, however for me it's a bit random.

Se in example this action result: https://github.com/nearform/node-clinic-doctor/pull/334/checks?check_run_id=893222994#step:5:426

From the stack trace you can see it appears to not be related to `MultiStream`.

I think there may be some issues related to the node process running out of memory and closing streams, or at least a sub-optimal shutdown procedure that may randomly result in this error.

**Comment by RafaelGSS** [comment]
> Same here. I'm using node v12.13.0.
> 
> ```
> Analysing dataError: premature close
>     at onclosenexttick (/usr/lib/node_modules/clinic/node_modules/end-of-stream/index.js:53:86)
>     at processTicksAndRejections (internal/process/task_queues.js:75:11)
> ```
> 
> Steps to repro:
> 
> 1. Generate [Moleculer demo project](https://moleculer.services/docs/0.13/usage.html#Create-a-Moleculer-project)
> 2. Open the generated project, set `transporter` to `null` in `moleculer.config.js`
> 3. Run `clinic doctor -- npm run dev`
> 4. Run `autocannon http://localhost:3000/api/greeter/hello`
> 5. Press `Ctrl + C`

I have just tried to reproduce it but looks like fixed in the latest version of clinic + node v16. 

Note: if you are still running into this problem, please provide a reproduction code and feel free to open a new issue.

**Comment by jtwebman** [comment]
Dang, that sucks we are not on Node.js 16 yet!

**Comment by RafaelGSS** [comment]
When it happens, I recommend you to:

- Remove the `.clinic` folder
- Remove all the `node_trace.*.log` files
- If you are running the autocannon for a small period of time, increase it.

**Comment by chrisdopuch** [comment]
I am also running into this problem.
Clinic version: v11.1.0
NodeJS version: v16.14.2
I am running the `--autocannon` option with 120 secs duration
I have tried deleting the `.clinic` folder but the error still persists. 

```
[==  ] Analysing dataError: premature close
    at onclosenexttick (/Users/me/.config/yarn/global/node_modules/end-of-stream/index.js:53:86)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
error Command failed with exit code 1.
```
